# Generated by Django 5.2.6 on 2025-09-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_payment_alter_booking_schedule_and_more'),
    ]

    operations = [
    ]
