# Generated by Django 5.1.6 on 2025-03-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(default='cb28de255cea', max_length=12, unique=True),
        ),
    ]
