# Generated by Django 5.1.6 on 2025-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_ticket_booking_alter_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(default='6c76b51edc7c', max_length=12, unique=True),
        ),
    ]
