# Generated by Django 5.1.6 on 2025-03-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(default='c5cd430e00ab', max_length=12, unique=True),
        ),
    ]
