# Generated by Django 5.1.6 on 2025-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(default='9f12f53f82e6', max_length=12, unique=True),
        ),
    ]
