# Generated by Django 5.1.6 on 2025-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(default='ed4c73ae4b77', max_length=12, unique=True),
        ),
    ]
