# Generated by Django 5.1.6 on 2025-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
