# Generated by Django 5.1.7 on 2025-03-13 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_seat_number_seat_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default=2, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
