# Generated by Django 5.1.7 on 2025-03-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_booking_seat_number_remove_ticket_pnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='AC', max_length=10),
        ),
    ]
