# Generated by Django 5.1.7 on 2025-03-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_booking_price_alter_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='booking.seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='booking.booking'),
        ),
    ]
