# Generated by Django 5.1.7 on 2025-03-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_bus_price_bus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=10),
        ),
    ]
