# Generated by Django 5.1.7 on 2025-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_bus_price_alter_bus_route_alter_bus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=12),
        ),
    ]
