# Generated by Django 5.1.7 on 2025-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_alter_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=10),
        ),
    ]
