# Generated by Django 5.1.7 on 2025-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_bus_seat_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_seats', models.IntegerField(help_text='Minimum number of seats to avail this discount', unique=True)),
                ('discount_percentage', models.FloatField(help_text='Discount percentage')),
            ],
        ),
    ]
