# Generated by Django 5.1.7 on 2025-03-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_discountsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoutePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus')),
            ],
        ),
    ]
