# Generated by Django 5.1.7 on 2025-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_bus_is_ac_routeprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeprice',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='routeprice',
            name='bus',
        ),
        migrations.AddField(
            model_name='routeprice',
            name='ac_increment_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='routeprice',
            name='route',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
