# Generated by Django 5.1.7 on 2025-03-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_rename_price_routeprice_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeprice',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
    ]
