# Generated by Django 5.1.7 on 2025-03-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_busstop_busroute_routestop_busroute_stops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={},
        ),
        migrations.RenameField(
            model_name='routestop',
            old_name='route',
            new_name='bus_route',
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('bus_route', 'stop')},
        ),
        migrations.AddField(
            model_name='routestop',
            name='arrival_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestop',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='order',
        ),
    ]
