# Generated by Django 5.1.7 on 2025-03-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_routestop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
