# Generated by Django 5.1.7 on 2025-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_alter_routestop_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
