# Generated by Django 5.1.7 on 2025-03-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_alter_routestop_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountSettings',
        ),
    ]
