# Generated by Django 5.1.7 on 2025-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_delete_discountsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_layout',
            field=models.TextField(default='[["1", "2", "aisle", "3", "4"], ["5", "6", "aisle", "7", "8"], ["9", "10", "aisle", "11", "12"], ["13", "14", "aisle", "15", "16"], ["17", "18", "aisle", "19", "20"], ["21", "22", "aisle", "23", "24"]]'),
        ),
    ]
