# Generated by Django 5.1.7 on 2025-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_alter_bus_seat_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_seats', models.IntegerField(help_text='Minimum seats required for discount')),
                ('discount_percentage', models.FloatField(help_text='Discount percentage')),
            ],
        ),
    ]
