# Generated by Django 5.1.7 on 2025-03-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeprice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
