# Generated by Django 5.1.7 on 2025-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_alter_routeprice_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeprice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
