# Generated by Django 5.1.7 on 2025-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
