# Generated by Django 5.1.7 on 2025-03-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(max_length=101),
        ),
    ]
