# Generated by Django 5.1.7 on 2025-03-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_alter_booking_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
