# Generated by Django 5.1.7 on 2025-03-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_email',
            field=models.EmailField(default='ram123@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(default='ram', max_length=100),
        ),
    ]
