# Generated by Django 5.1.7 on 2025-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_booking_passenger_age_booking_passenger_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(max_length=100),
        ),
    ]
