# Generated by Django 5.1.7 on 2025-03-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_alter_booking_passenger_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busroute',
            name='ending_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_routes', to='booking.busstop'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='starting_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='booking.busstop'),
        ),
        migrations.AddField(
            model_name='seat',
            name='bookings',
            field=models.ManyToManyField(related_name='seat_bookings', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='booking_seats', to='booking.seat'),
        ),
    ]
