# Generated by Django 5.1.7 on 2025-03-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_remove_booking_email_booking_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='ending_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ending_routes', to='booking.busstop'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='starting_stop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='booking.busstop'),
        ),
    ]
