# Generated by Django 5.1.7 on 2025-03-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_alter_busroute_ending_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='ending_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_routes', to='booking.busstop'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='starting_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='booking.busstop'),
        ),
    ]
