# Generated by Django 5.1.7 on 2025-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_alter_busroute_ending_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ending_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='starting_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
