# Generated by Django 5.1.7 on 2025-03-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_booking_ending_point_booking_starting_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ending_point',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starting_point',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
