# Generated by Django 5.1.7 on 2025-03-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_alter_booking_ending_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
    ]
