# Generated by Django 5.1.7 on 2025-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_remove_seat_bookings_seat_is_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='intermediate_stops',
            field=models.JSONField(default=list),
        ),
    ]
