# Generated by Django 5.1.7 on 2025-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_booking_intermediate_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='ending_stop',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='starting_stop',
        ),
        migrations.AddField(
            model_name='bus',
            name='intermediate_stops',
            field=models.JSONField(default=list),
        ),
    ]
