# Generated by Django 5.1.7 on 2025-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_remove_busroute_ending_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
