# Generated by Django 5.1.7 on 2025-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_alter_routestop_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
