# Generated by Django 5.1.7 on 2025-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='timing',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
