# Generated by Django 5.1.7 on 2025-03-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_bus_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ending_point',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='starting_point',
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='booking.bus')),
            ],
        ),
    ]
