# Generated by Django 5.1.7 on 2025-04-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0062_busschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.busschedule'),
            preserve_default=False,
        ),
    ]
