# Generated by Django 5.1.7 on 2025-04-04 18:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0063_booking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busschedule',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='busschedule',
            unique_together={('bus', 'date')},
        ),
    ]
