# Generated by Django 5.1.7 on 2025-04-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_busschedule_date_busschedule_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busschedule',
            name='available_seats',
        ),
    ]
