# Generated by Django 5.1.7 on 2025-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_remove_busschedule_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
