# Generated by Django 5.1.7 on 2025-04-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0067_booking_cancelled_at_booking_refund_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
