# Generated by Django 5.1.7 on 2025-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_alter_busschedule_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='intermediate_stops',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
