# Generated by Django 5.1.7 on 2025-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0069_alter_booking_intermediate_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='seat_number',
            field=models.CharField(max_length=11),
        ),
    ]
