# Generated by Django 5.1.7 on 2025-04-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0070_alter_seatbooking_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
