# Generated by Django 5.1.7 on 2025-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_alter_seatbooking_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
