# Generated by Django 5.1.7 on 2025-04-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0075_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
