# Generated by Django 5.1.7 on 2025-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0079_alter_bus_seat_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
