# Generated by Django 5.1.7 on 2025-04-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0080_alter_bus_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
