# Generated by Django 5.1.7 on 2025-04-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0081_seatbooking_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='intermediate_stops',
        ),
    ]
