# Generated by Django 5.1.7 on 2025-04-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0082_remove_booking_intermediate_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeprice',
            name='ac_increment_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
